from django.contrib.auth.hashers import make_password, check_password
from django.db import models

class Student(models.Model):
    """
    Represents a user (Student or Teacher) of the system.
    Handles Authentication (Phase 0) & Session Control.
    """
    phone_number = models.CharField(max_length=50, unique=True, help_text="WhatsApp phone number (Primary Key for Session)")
    name = models.CharField(max_length=100, blank=True, null=True, help_text="User's name")
    role = models.CharField(max_length=20, choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student')
    
    # Auth Fields
    password = models.CharField(max_length=128, help_text="Hashed Password", blank=True)
    is_authenticated = models.BooleanField(default=False, help_text="Is the user currently logged in?")
    created_at = models.DateTimeField(auto_now_add=True)

    def set_password(self, raw_password):
        self.password = make_password(raw_password)
    
    def check_password(self, raw_password):
        return check_password(raw_password, self.password)

    def __str__(self):
        return f"{self.phone_number} ({self.role}) - Auth: {self.is_authenticated}"

class ConversationLog(models.Model):
    """
    Stores the history of interactions between users and Chef Edwin.
    Privacy: Linked to Student via Foreign Key for strict data isolation.
    """
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='logs', help_text="The authenticated student this conversation belongs to")
    sender_number = models.CharField(max_length=50, help_text="WhatsApp number (redundant for admin display)")
    role = models.CharField(max_length=20, choices=[('student', 'Student'), ('teacher', 'Teacher')])
    message_body = models.TextField(help_text="Message sent by the user")
    chef_response = models.TextField(help_text="Response generated by Chef Edwin")
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.student.phone_number} ({self.role}) at {self.timestamp}"
