# Generated by Django 5.2.9 on 2025-12-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_number', models.CharField(help_text='WhatsApp number of the sender', max_length=50)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20)),
                ('message_body', models.TextField(help_text='Message sent by the user')),
                ('chef_response', models.TextField(help_text='Response generated by Chef Edwin')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
