# Generated by Django 5.2.9 on 2025-12-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='WhatsApp phone number', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text="User's name (optional)", max_length=100, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Has the user entered the correct password?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
