# Generated by Django 5.2.9 on 2025-12-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='student',
            name='is_authenticated',
            field=models.BooleanField(default=False, help_text='Is the user currently logged in?'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, help_text='Hashed Password', max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, help_text="User's name", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(help_text='WhatsApp phone number (Primary Key for Session)', max_length=50, unique=True),
        ),
    ]
