# Generated by Django 5.2.9 on 2025-12-16 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_remove_student_is_verified_student_is_authenticated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationlog',
            name='student',
            field=models.ForeignKey(default=1, help_text='The authenticated student this conversation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='assistant.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversationlog',
            name='sender_number',
            field=models.CharField(help_text='WhatsApp number (redundant for admin display)', max_length=50),
        ),
    ]
